---
- name: Deploy sudo
  import_playbook: sudo.yml

- name: Configure host os
  hosts: servers
  become: True
  tasks:
    - import_tasks: os-configure.yml

- name: Configure passtrough for Google Coral and AMD iGPU
  hosts: servers
  become: True
  tasks:
    - import_tasks: os-passtrough.yml
  handlers:
    - name: Reboot
      reboot:

- name: Deploy frigate
  hosts: servers
  tasks:
  - import_tasks: frigate.yml

- name: Google rclone sync
  hosts: servers
  become: True
  tasks:
    - import_tasks: rclone.yml
  vars:
    rclone_remote_name: "GoogleDrive"
    source_dir: "/var/lib/frigate/storage/exports"
    dest_path: "Videos/Monitoring"
